### PR TITLE
Upgrade to py3.9

### PR DESCRIPTION
**Pull request by AlpAribal**
# Description

Bumps the python version in the base image to 3.9 and refreezes requirements with py3.9. All frozen requirements were updated to their latest suitable version.

I started with an empty requirements file so that the hashes were not reused. In this case, pip-compile generates hashes for all binaries/wheels of the package, which is the reason for the huge diff in reqs.txt

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Refactoring including code style reformatting 
- [ ] Other (please describe):

# Checklist:

- [ ] I have read the [contributing guideline doc](https://squirrel-datasets-core.readthedocs.io/en/latest/code_of_conduct.html) (external contributors only)
- [x] Lint and unit tests pass locally with my changes
- [x] I have kept the PR small so that it can be easily reviewed  
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] All dependency changes have been reflected in the pip requirement files.

### CODE REVIEW

**Comment by AlpAribal** [comment]
The build is failing since the base image is not updated (only gets updated after merging to main) but the reqs are.

**Review by winfried-loetzsch — APPROVED** [review]
Thanks a lot Alp! I think the failing cloud build will be green after the base image has been rebuilt - If you agree I can trigger the main build for this branch to check

**Comment by AlpAribal** [comment]
> If you agree I can trigger the main build for this branch to check

I did not know it was possible, yes please, would be great!

**Comment by AlpAribal** [comment]
> Also can we change the python version in setup.py?

We still want to support py3.8, so won't bump the version there.

**Review by winfried-loetzsch — APPROVED** [review]
LG!

**Pull request merged**
